# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyColorMemo_1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift','=10.1.4'

  # Pods for MyColorMemo_1

  target 'MyColorMemo_1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyColorMemo_1UITests' do
    # Pods for testing
  end

end
